spring:
  datasource:
    password: 'admin'
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/ecommerce
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/store/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/store
  application:
    name: ecommerce-API

server:
  port: '8080'

keycloak:
  resource: store-flutter
  auth-server-url: http://localhost:8080
  realm: store
  public-client: true
  principal-attribute: preferred_username